[package]
name = "sonus-v"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
claxon = "0.4.3"
plotters = "0.3.4"
stft = { git = "https://github.com/leana8959/stft.git" }
